### ISSUE TITLE
Support for Android Q

### ISSUE THREAD

**Issue by paulo-raca** [PAGalaxyLab/YAHFA#113]
Hello, did you try supporting Android Q already?

**Comment by rk700** [comment]
No. Maybe I'd wait until it's released.

**Comment by domi-fa** [comment]
同求～

**Comment by enjoyMiracle** [comment]
同求

**Comment by yaeio** [comment]
Android Q is already released !
:) 
don't leave this great project alone

**Comment by paulo-raca** [comment]
We have had that for a while in our internal repository, I've finally added it in a PR: #122

Now I'm going to open a ticket for android R :rofl:

**Comment by rk700** [comment]
Merged. Thank you @paulo-raca and @yahe

**Comment by paulo-raca** [comment]
Thanks!

Now I'm going to open one for Android 11 :joy:
