### ISSUE TITLE
Android8.1 nexus6p上 自己编译的系统HOOK返回有问题。

### ISSUE THREAD

**Issue by IamHuskar** [PAGalaxyLab/YAHFA#116]
比如 StrartsWith    hook函数里面
如果 return backup(thiz,prefix);会返回原值 true.
直接return false 是 返回false

也就是 进入了 hook in String.startsWith.但是执行backup的时候异常了？

![ax2](https://user-images.githubusercontent.com/6307407/70621840-7a6d4200-1c55-11ea-94c2-865f66075452.png)

**Comment by IamHuskar** [comment]
我傻逼了。backup就是原函数。原来代码中得backup函数 实际上只是一个占位符。backup调用得就是返回原来得函数。尴尬了。~~~~

**Comment by 767972675** [comment]
> 我傻逼了。backup就是原函数。

我也是hook自己编译的系统，但是我发现service.jar里面的class都无法hook，大佬你知道怎么解决吗
