### ISSUE TITLE
YAHFA 如何hook service.jar里的类

### ISSUE THREAD

**Issue by 767972675** [PAGalaxyLab/YAHFA#119]
service.jar 不被 Bootstrap Class Loader 加载，所以Class.forName(String name);是找不到 service.jar的类的

**Comment by wjy000** [comment]
你要记住一个原则,hook谁就要注入到谁的进程,你要hook service,那就必须注入system_server进程

**Comment by 767972675** [comment]
> 你要记住一个原则,hook谁就要注入到谁的进程,你要hook service,那就必须注入system_server进程

已经搞定了，多谢
