### ISSUE TITLE
Hook the return of the function

### ISSUE THREAD

**Issue by thelittlefireman** [PAGalaxyLab/YAHFA#127]
Hi, is there a way to invert the hook : 
Call the original method first then hook the last instruction or the return of this function ?

Thanks

**Comment by rk700** [comment]
No, because entrypoint replacement is used in YAHFA instead of inline hook. But you can invoke the original method at the beginning of the hook and apply changes to the return result of the target method.

**Comment by thelittlefireman** [comment]
Thanks :)
