### ISSUE TITLE
java.lang.ClassNotFoundException: lab.galaxy.yahfa.HookInfo

### ISSUE THREAD

**Issue by pony5551** [PAGalaxyLab/YAHFA#135]
public static void doHookDefault(ClassLoader patchClassLoader, ClassLoader originClassLoader) {
        try {
            **Class<?> hookInfoClass = Class.forName("lab.galaxy.yahfa.HookInfo", true, patchClassLoader);** //这行代码报错
            String[] hookItemNames = (String[]) hookInfoClass.getField("hookItemNames").get(null);
            for (String hookItemName : hookItemNames) {
                doHookItemDefault(patchClassLoader, hookItemName, originClassLoader);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

android 8 和android 10都试过了
patchClassLoader加载正常的

**Comment by pony5551** [comment]
android 9也测试过，一样

**Comment by rk700** [comment]
类没有找到，可能是dex没有正常加载，需要再确认下dex文件是否可读

**Comment by pony5551** [comment]
> 类没有找到，可能是dex没有正常加载，需要再确认下dex文件是否可读

给过权限了，用的官方的代码没改动过跑的！

**Comment by rk700** [comment]
在这一步hook都还没有开始，应该和hook本身无关，可以再对classloader再试下不同类的加载

**Comment by pony5551** [comment]
问题解决了，要把原来的apk copy到app缓存文件夹再加载

**Comment by Qi-Ming** [comment]
请问怎么解决的，发生了类似问题Caused by: java.lang.ClassNotFoundException: Didn't find class "lab.galaxy.yahfa.HookInfo" on path: DexPathList[[zip file "/storage/emulated/0/demoPlugin-debug.apk"]

**Comment by ZR-RAN** [comment]
grant external storage permission to the app
