### ISSUE TITLE
新版本不能hook,io.github.pagalaxylab:yahfa:0.10.0这版本可以

### ISSUE THREAD

**Issue by pony5551** [PAGalaxyLab/YAHFA#138]
新版本io.github.pagalaxylab:yahfa:0.11.0 不能hook

下载回去直接用源码也不能hook

必须使用io.github.pagalaxylab:yahfa:0.10.0这个版本才可以hook成功

**Comment by rk700** [comment]
系统版本是什么，报什么错

这两个版本之间的commit应该不多，可以二分定位

**Comment by pony5551** [comment]
任意创建一个app,然后把library拖进去，引用好了，就是不行，上一个版本可以！
hook时提示都是正常的！
8.0
9.0
10.0都测试了，

但是神奇的是用github上下载的源码编译是可以的！
我创建app的姿势不正确吗？
 我对比了源码没啥问题啊！hook时也会显示被hook了，备份了！

**Comment by pony5551** [comment]
[test1.zip](https://github.com/PAGalaxyLab/YAHFA/files/5713372/test1.zip)
这是工程，很奇怪

**Comment by pony5551** [comment]
问题重开贴了
