### ISSUE TITLE
请问是否有支持XPoesd的api？

### ISSUE THREAD

**Issue by nnjun** [PAGalaxyLab/YAHFA#148]
同标题。

**Comment by necuil** [comment]
可以仿照edxposed和sandhook的实现，用dexmaker自己写一个（或者把两者的魔改一下），很容易的

**Comment by github-gsjb** [comment]
> 可以仿照edxposed和sandhook的实现，用dexmaker自己写一个（或者把两者的魔改一下），很容易的。实际上完全可以写一个通用的xposedcompat

有偿

**Comment by necuil** [comment]
> > 可以仿照edxposed和sandhook的实现，用dexmaker自己写一个（或者把两者的魔改一下），很容易的。实际上完全可以写一个通用的xposedcompat
> 
> 有偿

留电报账号

**Comment by github-gsjb** [comment]
> > > 可以仿照edxposed和sandhook的实现，用dexmaker自己写一个（或者把两者的魔改一下），很容易的。实际上完全可以写一个通用的xposedcompat
> > 
> > 
> > 有偿
> 
> 留电报账号

tg_gsjb
