### ISSUE TITLE
does this support Android 12 factory release image?

### ISSUE THREAD

**Issue by vegedreamgagnoa** [PAGalaxyLab/YAHFA#153]
I saw that library-release.aar is for Android R / 11. Does YAHFA provide support for Android 12 factory release/public image?

Thanks!

tag @rk700 @rk700

**Comment by rk700** [comment]
Not yet. Some native hooks are required to fix the issue but I haven't figured it out. https://github.com/PAGalaxyLab/YAHFA/issues/151

**Comment by vegedreamgagnoa** [comment]
@rk700 I tried to hook FixupStaticTrampolines but didn't solve the issue, fixing the classlinker offset/pointer not helping either. I keep exploring as well.

**Comment by lianglixin** [comment]
你可以稍微思考一下为啥给系统库函数挂钩不会崩溃？是否和dex2oat优化以后有关？是否可以像SandHook在安卓7之前使用的挂钩方法一样？
这几个问题你可以思考一下，100%可以解决这个问题。

**Comment by vegedreamgagnoa** [comment]
@lianglixin maybe inlining could be the issue, I am still looking at it.
meanwhile is there any method that we could use to hook without relying on those Art structures? Something like using unsafe & libcore.io.memory as described here https://windysha.github.io/2018/01/15/Android%E7%83%AD%E4%BF%AE%E5%A4%8D%E6%A1%86%E6%9E%B6AndFix%E6%A0%B8%E5%BF%83%E4%BB%A3%E7%A0%81%E5%88%86%E6%9E%90%E4%BB%A5%E5%8F%8A%E7%BA%AFJava%E4%BB%A3%E7%A0%81%E5%AE%9E%E7%8E%B0AndFix/

**Comment by vegedreamgagnoa** [comment]
Solved, I got it working now to hook successfully on Android 12

**Comment by beaver-android** [comment]
@vegedreamgagnoa What was the problem and how did you solve it?
