### ISSUE TITLE
`shouldVisiblyInit` on x86 platform

### ISSUE THREAD

**Issue by ZR-RAN** [PAGalaxyLab/YAHFA#156]
Previously, `shouldVisiblyInit` returns 0 on x86 platform, but after commit <a href='https://github.com/PAGalaxyLab/YAHFA/commit/60bedadd073af6f2c867429665db676de37aab6c' target='_blank'>60bedad</a> it returns 1. Is this intended or not?
```c++
static int shouldVisiblyInit() {
#if defined(__i386__) || defined(__x86_64__)
    return 0;
#else
    if(SDKVersion < __ANDROID_API_R__) {
        return 0;
    }
    else return 1;
#endif
}
```
```c++
static int shouldVisiblyInit() {
#if defined(__i386__) || defined(__x86_64__)
    return 1;
#else
    if(SDKVersion < __ANDROID_API_R__) {
        return 0;
    }
    else return 1;
#endif
}
```

**Comment by rk700** [comment]
Oh yes that's a bug. Thank you for filing it. Would you make a pull request?

**Comment by ZR-RAN** [comment]
Thanks, but I am not inclined to make a pull request.
