### ISSUE TITLE
support android 12 better.

### ISSUE THREAD

**Issue by WindySha** [PAGalaxyLab/YAHFA#163]
OFFSET_classlinker_in_Runtime should be 472 + 8 in the newest android 12 version.

**Comment by yearsyan** [comment]
I think the better way to get classlinker address is the relative offset of JavaVMExt address which is easy to get by JNI.
In a art::Runtime instance, whether android 11 or android 12, the offset is 3 pointer size.
```
ClassLinker* class_linker_;

SignalCatcher* signal_catcher_;

std::unique_ptr<jni::JniIdManager> jni_id_manager_;

std::unique_ptr<JavaVMExt> java_vm_;
```

**Comment by rk700** [comment]
> I think the better way to get classlinker address is the relative offset of JavaVMExt address which is easy to get by JNI. In an art::Runtime instance, whether android 11 or android 12, the offset is 3 pointer size.
> 
> ```
> ClassLinker* class_linker_;
> 
> SignalCatcher* signal_catcher_;
> 
> std::unique_ptr<jni::JniIdManager> jni_id_manager_;
> 
> std::unique_ptr<JavaVMExt> java_vm_;
> ```

Thanks! That's a good idea. I just pushed a new commit for it: 9cea98bd749164c011ac44d35c32c2a0e4b146c6

**Comment by yujincheng08** [comment]
@rk700 
Not actually true: https://android.googlesource.com/platform/art/+/4dcac3629ea5925e47b522073f3c49420e998911

**Comment by yearsyan** [comment]
> @rk700 Not actually true: https://android.googlesource.com/platform/art/+/4dcac3629ea5925e47b522073f3c49420e998911
> 
> ```diff
> diff --git [a/runtime/runtime.h](https://android.googlesource.com/platform/art/+/48fb9f43a81fa0cab09ed4a4f3d478c1a0ecbe9e/runtime/runtime.h) [b/runtime/runtime.h](https://android.googlesource.com/platform/art/+/4dcac3629ea5925e47b522073f3c49420e998911/runtime/runtime.h)
> index 2dd022e..0c99cf9 100644
> --- a/runtime/runtime.h
> +++ b/runtime/runtime.h
> @@ -107,6 +107,7 @@
>  struct RuntimeArgumentMap;
>  class RuntimeCallbacks;
>  class SignalCatcher;
> +class SmallIrtAllocator;
>  class StackOverflowHandler;
>  class SuspensionHandler;
>  class ThreadList;
> @@ -324,6 +325,10 @@
>      return class_linker_;
>    }
>  
> +  SmallIrtAllocator* GetSmallIrtAllocator() const {
> +    return small_irt_allocator_;
> +  }
> +
>    jni::JniIdManager* GetJniIdManager() const {
>      return jni_id_manager_.get();
>    }
> @@ -1198,6 +1203,8 @@
>  
>    SignalCatcher* signal_catcher_;
>  
> +  SmallIrtAllocator* small_irt_allocator_;
> +
>    std::unique_ptr<jni::JniIdManager> jni_id_manager_;
>  
>    std::unique_ptr<JavaVMExt> java_vm_;
> ```

Excuse my ignorance when will this change take effect, In Android 13 or with Android12 update?

**Comment by rk700** [comment]
So the distance between classlinker and javavm is increased by 1 pointer right?

**Comment by canyie** [comment]
I think you are right. And I think we can try to dlsym some symbols added in this commit (just like https://github.com/canyie/pine/commit/34dc23e34f600f6c44092a2c2a7c66e9fa30b994) to detect if the rom merged this commit.

**Comment by shuajinanhai** [comment]
是的，我用小米6刷过12系统测试过，获取到的是错误的值。不过也有其他12系统刷机包，获取到的是正确的值。另外安卓13测试过，也是错误的
