### ISSUE TITLE
一些关于热修复的应用 

### ISSUE THREAD

**Issue by WangYinuo** [PAGalaxyLab/YAHFA#95]
在9.0中似乎有些限制，相同名字的类不会被加载两次，如果能突破这个限制，这个框架也许可以实现9.0上的如修复

**Comment by rk700** [comment]
没明白什么意思，并没有相同名字的类

**Comment by WangYinuo** [comment]
抱歉  我没有说清楚  我的意思是 您代码中没有同名类，我想如果我想用您这种类似方法 实现9.0上的热修复的话 需要把所有的方法都改名
